// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/telemetry/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid          int32                  `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Executable    string                 `protobuf:"bytes,3,opt,name=executable,proto3" json:"executable,omitempty"`
	CommandLine   string                 `protobuf:"bytes,4,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_pkg_telemetry_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_telemetry_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_pkg_telemetry_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessEvent) GetPpid() int32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessEvent) GetExecutable() string {
	if x != nil {
		return x.Executable
	}
	return ""
}

func (x *ProcessEvent) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *ProcessEvent) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type NetworkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	LocalIp       string                 `protobuf:"bytes,3,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	RemoteIp      string                 `protobuf:"bytes,4,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	RemotePort    int32                  `protobuf:"varint,5,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_pkg_telemetry_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_telemetry_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_pkg_telemetry_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkEvent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NetworkEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEvent) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *NetworkEvent) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *NetworkEvent) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Hostname  string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to EventData:
	//
	//	*Event_Process
	//	*Event_Network
	EventData     isEvent_EventData `protobuf_oneof:"event_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pkg_telemetry_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_telemetry_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pkg_telemetry_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetEventData() isEvent_EventData {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *Event) GetProcess() *ProcessEvent {
	if x != nil {
		if x, ok := x.EventData.(*Event_Process); ok {
			return x.Process
		}
	}
	return nil
}

func (x *Event) GetNetwork() *NetworkEvent {
	if x != nil {
		if x, ok := x.EventData.(*Event_Network); ok {
			return x.Network
		}
	}
	return nil
}

type isEvent_EventData interface {
	isEvent_EventData()
}

type Event_Process struct {
	Process *ProcessEvent `protobuf:"bytes,3,opt,name=process,proto3,oneof"`
}

type Event_Network struct {
	Network *NetworkEvent `protobuf:"bytes,4,opt,name=network,proto3,oneof"`
}

func (*Event_Process) isEvent_EventData() {}

func (*Event_Network) isEvent_EventData() {}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pkg_telemetry_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_telemetry_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_telemetry_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_telemetry_telemetry_proto protoreflect.FileDescriptor

const file_pkg_telemetry_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/telemetry/telemetry.proto\x12\ttelemetry\"\xa3\x01\n" +
	"\fProcessEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\x05R\x04ppid\x12\x1e\n" +
	"\n" +
	"executable\x18\x03 \x01(\tR\n" +
	"executable\x12!\n" +
	"\fcommand_line\x18\x04 \x01(\tR\vcommandLine\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\"\x95\x01\n" +
	"\fNetworkEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x19\n" +
	"\blocal_ip\x18\x03 \x01(\tR\alocalIp\x12\x1b\n" +
	"\tremote_ip\x18\x04 \x01(\tR\bremoteIp\x12\x1f\n" +
	"\vremote_port\x18\x05 \x01(\x05R\n" +
	"remotePort\"\xb9\x01\n" +
	"\x05Event\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x123\n" +
	"\aprocess\x18\x03 \x01(\v2\x17.telemetry.ProcessEventH\x00R\aprocess\x123\n" +
	"\anetwork\x18\x04 \x01(\v2\x17.telemetry.NetworkEventH\x00R\anetworkB\f\n" +
	"\n" +
	"event_data\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2E\n" +
	"\n" +
	"EDRService\x127\n" +
	"\fStreamEvents\x12\x10.telemetry.Event\x1a\x13.telemetry.Response(\x01B\x18Z\x16edr-core/pkg/telemetryb\x06proto3"

var (
	file_pkg_telemetry_telemetry_proto_rawDescOnce sync.Once
	file_pkg_telemetry_telemetry_proto_rawDescData []byte
)

func file_pkg_telemetry_telemetry_proto_rawDescGZIP() []byte {
	file_pkg_telemetry_telemetry_proto_rawDescOnce.Do(func() {
		file_pkg_telemetry_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_telemetry_telemetry_proto_rawDesc), len(file_pkg_telemetry_telemetry_proto_rawDesc)))
	})
	return file_pkg_telemetry_telemetry_proto_rawDescData
}

var file_pkg_telemetry_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_telemetry_telemetry_proto_goTypes = []any{
	(*ProcessEvent)(nil), // 0: telemetry.ProcessEvent
	(*NetworkEvent)(nil), // 1: telemetry.NetworkEvent
	(*Event)(nil),        // 2: telemetry.Event
	(*Response)(nil),     // 3: telemetry.Response
}
var file_pkg_telemetry_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.Event.process:type_name -> telemetry.ProcessEvent
	1, // 1: telemetry.Event.network:type_name -> telemetry.NetworkEvent
	2, // 2: telemetry.EDRService.StreamEvents:input_type -> telemetry.Event
	3, // 3: telemetry.EDRService.StreamEvents:output_type -> telemetry.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_telemetry_telemetry_proto_init() }
func file_pkg_telemetry_telemetry_proto_init() {
	if File_pkg_telemetry_telemetry_proto != nil {
		return
	}
	file_pkg_telemetry_telemetry_proto_msgTypes[2].OneofWrappers = []any{
		(*Event_Process)(nil),
		(*Event_Network)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_telemetry_telemetry_proto_rawDesc), len(file_pkg_telemetry_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_telemetry_telemetry_proto_goTypes,
		DependencyIndexes: file_pkg_telemetry_telemetry_proto_depIdxs,
		MessageInfos:      file_pkg_telemetry_telemetry_proto_msgTypes,
	}.Build()
	File_pkg_telemetry_telemetry_proto = out.File
	file_pkg_telemetry_telemetry_proto_goTypes = nil
	file_pkg_telemetry_telemetry_proto_depIdxs = nil
}
