// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: pkg/telemetry/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EDRService_StreamEvents_FullMethodName = "/telemetry.EDRService/StreamEvents"
)

// EDRServiceClient is the client API for EDRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EDRServiceClient interface {
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, Response], error)
}

type eDRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEDRServiceClient(cc grpc.ClientConnInterface) EDRServiceClient {
	return &eDRServiceClient{cc}
}

func (c *eDRServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EDRService_ServiceDesc.Streams[0], EDRService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_StreamEventsClient = grpc.ClientStreamingClient[Event, Response]

// EDRServiceServer is the server API for EDRService service.
// All implementations must embed UnimplementedEDRServiceServer
// for forward compatibility.
type EDRServiceServer interface {
	StreamEvents(grpc.ClientStreamingServer[Event, Response]) error
	mustEmbedUnimplementedEDRServiceServer()
}

// UnimplementedEDRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEDRServiceServer struct{}

func (UnimplementedEDRServiceServer) StreamEvents(grpc.ClientStreamingServer[Event, Response]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEDRServiceServer) mustEmbedUnimplementedEDRServiceServer() {}
func (UnimplementedEDRServiceServer) testEmbeddedByValue()                    {}

// UnsafeEDRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EDRServiceServer will
// result in compilation errors.
type UnsafeEDRServiceServer interface {
	mustEmbedUnimplementedEDRServiceServer()
}

func RegisterEDRServiceServer(s grpc.ServiceRegistrar, srv EDRServiceServer) {
	// If the following call panics, it indicates UnimplementedEDRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EDRService_ServiceDesc, srv)
}

func _EDRService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EDRServiceServer).StreamEvents(&grpc.GenericServerStream[Event, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EDRService_StreamEventsServer = grpc.ClientStreamingServer[Event, Response]

// EDRService_ServiceDesc is the grpc.ServiceDesc for EDRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EDRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.EDRService",
	HandlerType: (*EDRServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EDRService_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/telemetry/telemetry.proto",
}
