syntax = "proto3";

package api;

option go_package = "edr-core/pkg/api";

message ProcessEvent {
  int64 timestamp = 1;
  uint32 process_id = 2;
  uint32 parent_process_id = 3;
  string image_path = 4;
  string command_line = 5;
  string event_type = 6;
}

message EventResponse {
  bool success = 1;
}

message HeartbeatEvent {
  string agent_id = 1;
  string status = 2;
  int64 timestamp = 3;
}

service Telemetry {
  rpc SendEvent(ProcessEvent) returns (EventResponse);
  rpc SendHeartbeat(HeartbeatEvent) returns (EventResponse);
}
