// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/telemetry.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProcessId       uint32                 `protobuf:"varint,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ParentProcessId uint32                 `protobuf:"varint,3,opt,name=parent_process_id,json=parentProcessId,proto3" json:"parent_process_id,omitempty"`
	ImagePath       string                 `protobuf:"bytes,4,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	CommandLine     string                 `protobuf:"bytes,5,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"`
	EventType       string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_pkg_api_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProcessEvent) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *ProcessEvent) GetParentProcessId() uint32 {
	if x != nil {
		return x.ParentProcessId
	}
	return 0
}

func (x *ProcessEvent) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *ProcessEvent) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *ProcessEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TargetPid     uint32                 `protobuf:"varint,3,opt,name=target_pid,json=targetPid,proto3" json:"target_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_pkg_api_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *EventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EventResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EventResponse) GetTargetPid() uint32 {
	if x != nil {
		return x.TargetPid
	}
	return 0
}

type HeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_pkg_api_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NetworkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProcessId     uint32                 `protobuf:"varint,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	SourceIp      string                 `protobuf:"bytes,3,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort    uint32                 `protobuf:"varint,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestIp        string                 `protobuf:"bytes,5,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	DestPort      uint32                 `protobuf:"varint,6,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_pkg_api_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NetworkEvent) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *NetworkEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *NetworkEvent) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *NetworkEvent) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *NetworkEvent) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *NetworkEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

var File_pkg_api_telemetry_proto protoreflect.FileDescriptor

const file_pkg_api_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/telemetry.proto\x12\x03api\"\xd8\x01\n" +
	"\fProcessEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\rR\tprocessId\x12*\n" +
	"\x11parent_process_id\x18\x03 \x01(\rR\x0fparentProcessId\x12\x1d\n" +
	"\n" +
	"image_path\x18\x04 \x01(\tR\timagePath\x12!\n" +
	"\fcommand_line\x18\x05 \x01(\tR\vcommandLine\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\"`\n" +
	"\rEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_pid\x18\x03 \x01(\rR\ttargetPid\"a\n" +
	"\x0eHeartbeatEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xdb\x01\n" +
	"\fNetworkEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\rR\tprocessId\x12\x1b\n" +
	"\tsource_ip\x18\x03 \x01(\tR\bsourceIp\x12\x1f\n" +
	"\vsource_port\x18\x04 \x01(\rR\n" +
	"sourcePort\x12\x17\n" +
	"\adest_ip\x18\x05 \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\x06 \x01(\rR\bdestPort\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol2\xb4\x01\n" +
	"\tTelemetry\x122\n" +
	"\tSendEvent\x12\x11.api.ProcessEvent\x1a\x12.api.EventResponse\x128\n" +
	"\rSendHeartbeat\x12\x13.api.HeartbeatEvent\x1a\x12.api.EventResponse\x129\n" +
	"\x10SendNetworkEvent\x12\x11.api.NetworkEvent\x1a\x12.api.EventResponseB\x12Z\x10edr-core/pkg/apib\x06proto3"

var (
	file_pkg_api_telemetry_proto_rawDescOnce sync.Once
	file_pkg_api_telemetry_proto_rawDescData []byte
)

func file_pkg_api_telemetry_proto_rawDescGZIP() []byte {
	file_pkg_api_telemetry_proto_rawDescOnce.Do(func() {
		file_pkg_api_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_telemetry_proto_rawDesc), len(file_pkg_api_telemetry_proto_rawDesc)))
	})
	return file_pkg_api_telemetry_proto_rawDescData
}

var file_pkg_api_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_telemetry_proto_goTypes = []any{
	(*ProcessEvent)(nil),   // 0: api.ProcessEvent
	(*EventResponse)(nil),  // 1: api.EventResponse
	(*HeartbeatEvent)(nil), // 2: api.HeartbeatEvent
	(*NetworkEvent)(nil),   // 3: api.NetworkEvent
}
var file_pkg_api_telemetry_proto_depIdxs = []int32{
	0, // 0: api.Telemetry.SendEvent:input_type -> api.ProcessEvent
	2, // 1: api.Telemetry.SendHeartbeat:input_type -> api.HeartbeatEvent
	3, // 2: api.Telemetry.SendNetworkEvent:input_type -> api.NetworkEvent
	1, // 3: api.Telemetry.SendEvent:output_type -> api.EventResponse
	1, // 4: api.Telemetry.SendHeartbeat:output_type -> api.EventResponse
	1, // 5: api.Telemetry.SendNetworkEvent:output_type -> api.EventResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_telemetry_proto_init() }
func file_pkg_api_telemetry_proto_init() {
	if File_pkg_api_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_telemetry_proto_rawDesc), len(file_pkg_api_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_telemetry_proto_goTypes,
		DependencyIndexes: file_pkg_api_telemetry_proto_depIdxs,
		MessageInfos:      file_pkg_api_telemetry_proto_msgTypes,
	}.Build()
	File_pkg_api_telemetry_proto = out.File
	file_pkg_api_telemetry_proto_goTypes = nil
	file_pkg_api_telemetry_proto_depIdxs = nil
}
