apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: edr
      username: default
      tlsSkipVerify: true
      httpHeaders: []
    secureJsonData:
      password: bastion123
